export const LOGIN_CMD = 'LOGIN';

export const CREATE_USER_CMD = 'CREATE_USER';
export const UPDATE_USER_CMD = 'UPDATE_USER';
export const GET_USER_CMD = 'GET_USER';
export const FIND_USER_BY_EMAIL = 'FIND_USER_BY_EMAIL';
export const FIND_USER_BY_ID = "FIND_USER_BY_ID";
export const FIND_USER_BY_IDS = 'FIND_USER_BY_IDS';

export const CREATE_CLASS_CMD = 'CREATE_CLASS';
export const UPDATE_CLASS_CMD = 'UPDATE_CLASS';
export const DELETE_CLASS_CMD = 'DELETE_CLASS';
export const GET_CLASS_CMD = 'GET_CLASS';
export const FIND_ALL_CLASS_CMD = 'FIND_ALL_CLASS';
export const ADD_STUDENT_TO_CLASS_CMD = 'ADD_STUDENT_TO_CLASS';

export const CREATE_GRADE_CMD = 'CREATE_GRADE';
export const UPDATE_GRADE_CMD = 'UPDATE_GRADE';
export const DELETE_GRADE_CMD = 'DELETE_GRADE';
export const GET_GRADE_CMD = 'GET_GRADE';
export const FIND_GRADE_BY_STUDENT_CMD = 'FIND_GRADE_BY_STUDENT';
export const FIND_GRADE_BY_CLASS_CMD = 'FIND_GRADE_BY_CLASS';


export const DELETE_USER_CMD = 'DELETE_USER';


